### ISSUE TITLE
Testing if points are in hull or not

### ISSUE THREAD

**Issue by davidcsterratt** [davidcsterratt/geometry#1]
A user has written saying he wants to build a convex hull in R  and test whether points are  inside the convex hull or not. 

It's possible to triangulate the vertices of the hull using `delaunayn()` and then use `tsearchn()` to search through all the simplices of the hull to see if the point is included. However, this is going to be inefficient, especially as the number of dimensions increases.

The R geometry package is based on the qhull library. I have looked at the qhull documentation, and it seems that there is a function in its C code (`qh_findbestfacet()`) that would do the trick. I would need to link this into the R package, which I haven't done yet, though I would like to soon.

**Comment by joey711** [comment]
Looks like an example of an implementation was shared on R mailing list in 2009 (with some doc and profiling):

https://stat.ethz.ch/pipermail/r-help/2009-December/415353.html

I'm going to try and use the function shared there unless there's a tested alternative available in this package (or related) that you might suggest instead...

**Comment by davidcsterratt** [comment]
There is an alternative available in the development version of this package: `inhulln()`, which uses the  qhull library, so should be efficient.
(The commit didn't get attached to this issue as I didn't set the right commit message:
https://github.com/davidcsterratt/geometry/commit/7a658430de477bd0ded802d0b7041dba32943919#diff-b3a4e4e8a2970b848993dd7b8cf68def )
It passes the tests in this file:
https://github.com/davidcsterratt/geometry/blob/master/pkg/tests/testthat/test-inhulln.R
I'm hoping to release the version of geometry containing this code to CRAN very soon.
