### ISSUE TITLE
Bug in delaunayn with regularly spaced points

### ISSUE THREAD

**Issue by Jean-Romain** [davidcsterratt/geometry#10]
Hi, here a bug I found some days ago. When you run a triangulation of regularly spaced points sometime (but I can't find a pattern) algorithm fails. 

```r
library(geometry)

X = expand.grid(1:100, 1:100)
delaunayn(X)
# OK

X = expand.grid(seq(0.5,50,0.25), seq(0.5,50,0.25))
delaunayn(X)
# OK

X = expand.grid(seq(0.25,50,0.25), seq(0.5,50,0.25))
delaunayn(X)
# FAIL
```
```
QH6154 qhull precision error: initial facet 1 is coplanar with the interior point
Error in delaunayn(X) : Received error code 2 from qhull.
```
If you add a dummy point the problem does not occur anymore

```r
X = expand.grid(seq(0.25,50,0.25), seq(0.5,50,0.25))
X = rbind(X, -1,1)
delaunayn(X)
# OK
```
Since it happens in qhull and I don't know what is qhull I didn't investigate further.

**Comment by davidcsterratt** [comment]
Could you double-check this is a problem in the development version of geometry? I think this has been fixed in Issue #4 , but I haven't yet released this code to CRAN.

**Comment by Jean-Romain** [comment]
Right. I was using the released version at my office. At home with devel version it works and now using the devel version on my other computer it works too.

Do you have an rough idea of when you plan to release v0.4.0? 1, 2, 6 month?

**Comment by davidcsterratt** [comment]
Re release date, I had been hoping to get the tsearchn algorithm running with the Qhull library (https://github.com/davidcsterratt/geometry/issues/6). There is now of course the problem with the Qz option.
