### ISSUE TITLE
Returning non-triangulated facets from QHULL

### ISSUE THREAD

**Issue by pavlomozharovskyi** [davidcsterratt/geometry#22]
For the moment, the geometry package returns the QHULL output as a matrix with number of the columns (= number of vertices in each facet) equal to the space dimension. It would be nice to have a possibility of returning non-triangulated facets of the convex hull potentially having differing numbers of vertices.

**Comment by davidcsterratt** [comment]
I hadn't thought about adding the functionality that you desire, but it seems like an entirely reasonable request. We would need to do something like:

1. Add a flag (false by default) "return.non.triangulated.facets"? to `convhulln()` and `C_convhulln()`

2. If the flag is true, determine what the maximum number of vertices in a facet is and allocate idx to have that many columns.

3. Then ignore the warning if the flag is `TRUE`.

**Comment by pavlomozharovskyi** [comment]
Please let me suggest one more possibility to implement these changes:

The structure returned by the R-function "convhulln" if flag
"return.non.triangulated.facets" is set can also be a list, where each
entry corresponds to a facet and constitutes a vector of the indices of
the facet's vertices.

Disadvantages of this approach:

1) The output structure is not a matrix anymore, but for the users who
use the package already nothing will change, with the default value of
the flag a matrix of triangulated facets is returned.

2) Handling a matrix is simpler and faster as it allows for
vectorization of the operations.

3) Some more modifications on C-level will be needed, I guess.

Advantages of this approach:

1) More efficient memory usage. Imagine that convex hull of the data
contains one facet (or a few facets) only with a relatively large number
of vertices, more than other facets have on an average. In this case
substantial part of the matrix will be filled with NAs/-1s (filling
dummy elements), e.g.:

1 3 4 NA NA NA NA
...
3 7 9 4 NA NA NA
...
3 1 5 6 7 9 8
...
1 5 4 NA NA NA NA
...

2) Unless I miss a point (which is possible here), one should not go
through the output of the QHULL routine twice, which will be needed if
we want to estimate dimension of the matrix.

3) In R, when requesting the number of the vertices of a facet (number 3
say) one can have it directly by calling "length(output$hull[[3]])" and
does not need to involve a function counting number of nonNA/non-1
entries in a row of the matrix.


What do you think about this?

**Comment by davidcsterratt** [comment]
I'd thought of a list too, which is conceptually more elegant.

I rejected it because of the disadvantages you state. Re the advantages:

1. Yes, it would be more memory efficient, but how often will the sort of structures with one facet with many vertices actually occur?

2. Yes, we will have to go through the output of the Qhull routine, twice, but the first pass will be fast.

3. Yes, but it's not too hard to find the number of NAs in each row for a matrix, e.g.:
   ```
   a <- rbind(1:4, c(1:3, NA), 1:4)
   rowSums(apply(a, 2, is.na))
   ```
One further disadvantage of the list is that, if I'm not mistaken, there will have to be one allocVector() for every list member. For large convex hulls I think this could cause a big performance hit.

**Comment by pavlomozharovskyi** [comment]
I agree with your argumentation, in particular: work with matrices is usual for R and calling allocVector() each time may indeed be time consuming as convex hulls in dimensions >=3 may have many facets. So it makes sense to stick to your initial proposal. I will be glad to prepare a pull request, if this is ok for you?

**Comment by davidcsterratt** [comment]
Yes, please create a pull request. If you can create one or two tests at the same time, that would be great. In case you're not familiar with testthat, please look at the tests/testthat directory.

**Comment by davidcsterratt** [comment]
Now in version 0.4.0, being released to CRAN.
