### ISSUE TITLE
Intersection of two convex hulls

### ISSUE THREAD

**Issue by davidcsterratt** [davidcsterratt/geometry#26]
It would be good to be able to compute the intersection between two convex hulls, which is itself a convex hull:
https://math.stackexchange.com/questions/1687374/is-the-intersection-of-2-convex-hulls-a-convex-hull

**Comment by Bisaloo** [comment]
Hi, thank you for this function, it is very useful! I was wondering if you would be willing to downgrade the error L29

https://github.com/davidcsterratt/geometry/blob/d5c98e7fe391e5466b3e49c75a7001672c07862b/pkg/R/intersectn.R#L29

to a warning or a message and return an overlap of 0.

Downstream applications may use this function on convex hulls without knowing if they will overlap or not, possibly as a way to test exactly this. I think it would make more sense for this function to behave the same in all cases and simply return 0 when needed.

You can for example have a look at https://github.com/rmaia/pavo/pull/103 when we need to compute the overlap of two convex hulls.

**Comment by davidcsterratt** [comment]
The latest commits should address the problem with the error being returned when the hulls do not overlap.
