### ISSUE TITLE
memory misuse in src/Rtsearchn.c

### ISSUE THREAD

**Issue by BillDunlap** [davidcsterratt/geometry#40]
In src/Rtsearchn.c 'idmap' is allocated with max_facet_id elements but then you assign a value to idmap[max_facet_id], which is one element beyond the end of that allocation, potentially clobbering the memory allocation system.  (I noticed this when running the package in TERR, whose debug version checks that nothing writes beyond the end of an allocated array.)

The easiest solution is to allocate one more element in idmap.  One could also add a lot of -1's to the subscripts, mapping the R-style 1-based subscripts to C-style 0-based ones, but I think that would make it harder to read.
```
diff -ru /homes/bill/CRAN/geometry/src/Rtsearchn.c geometry/src/Rtsearchn.c
--- /homes/bill/CRAN/geometry/src/Rtsearchn.c   2019-02-17 14:59:44.000000000 -0800
+++ geometry/src/Rtsearchn.c    2019-08-14 08:51:10.936296000 -0700
@@ -77,12 +77,15 @@
     }
   }

-  int *idmap = (int *) R_alloc(max_facet_id, sizeof(int));
+  int *idmap = (int *) R_alloc(max_facet_id+1, sizeof(int));
   int i = 0;
   FORALLfacets {
     if (!facet->upperdelaunay) {
       i++;
       if (debug & 1) Rprintf("Facet id %d; index %d\n;", facet->id, i);
+      if (facet->id < 1 || facet->id > max_facet_id) {
+        Rf_error("facet_id %d (at index %d) is not in {1,...,%d}", facet->id, i, max_facet_id);
+      }
       idmap[facet->id] = i;
     }
   }
```

**Comment by davidcsterratt** [comment]
Thanks - I'll take a look at this.

**Comment by davidcsterratt** [comment]
Thanks - fix applied and I've credited you in the NEWS file. If you could double-check by running the package in TERR, that would be great.

**Comment by BillDunlap** [comment]
After the fix TERR doesn't find any more array overruns.

It does have problems with another issue that I think should
be fixed in R - R_tmpnam() returns some malloc'ed by R or TERR
but free'd by the DLL.  This works on Windows if the DLL and the
main executable are compiled by the same compiler, but we
compile TERR with both the Intel and Microsoft C/C++ compilers
and, at least with the Miscrosoft compiler, calling free() on the return
value of R_tmpnam causes the program to crash.  The geometry
package is one of the few that call R_tmpnam, which is why I was
looking more closely at it.  Unless I come up with a better solution,
I think I will ask R-core to add a freeing routine to go along with
R_tmpnam and R_tmnam2.

**Comment by davidcsterratt** [comment]
Thanks for checking this.

Re R_tmpnam(), it would be nice to avoid using it altogether. I recall trying to do this, but it proved tricky, at least with the additional constraint of making minimal changes to the Qhull sources.

It does sound that R_tmpnam()'s behaviour needs to be fixed at the R level. That's above my pay grade, so I'd be glad if you could work on it.

**Comment by BillDunlap** [comment]
If you are amenable to not calling R_tmpnam in the C code, here is a patch
that calls tempfile() in the R code to create the files to receive stdout
and stderr and passes the two file names to the C code instead of passing
the directory name.  Thus it avoids the call to free() in the C code.  It
passes all the testthat tests (in R and in both release and debug versions
of TERR).

Does that affect the interface to qhull?

**Comment by davidcsterratt** [comment]
I can't see the patch file. You could try doing a pull request, or attaching a file in the github interface.
