### ISSUE TITLE
Function "fdist" cannot be found in distmeshnd

### ISSUE THREAD

**Issue by LoutK** [davidcsterratt/geometry#48]
Function "fdist" cannot be found in distmeshnd.

> Error in fdist(p, ...) : could not find function "fdist"

I think it refers to: https://github.com/cran/geometry/blob/master/R/distmeshnd.R#L174

Can be reproduced by using this file:
[inputmatrix.txt](https://github.com/davidcsterratt/geometry/files/3973384/inputmatrix.txt)

```r
library(geometry)
n <- read.delim("inputmatrix.txt")
meshsphere <- mesh.dsphere(n, radius = 1)
meshh <- mesh.hunif(as.matrix(n))
dmesh <- distmeshnd(fdist = meshsphere, fh = meshh, h = 15, box = bbox(as.matrix(n)))

**Comment by davidcsterratt** [comment]
According to the help page, the `fdist` needs to be a:
> vectorized signed distance function, for example \code{\link{mesh.dsphere}}, accepting an \code{m}-by-\code{n} matrix, where \code{m} is arbitrary, as the first argument.

In the example it's a matrix:
```
> class(meshsphere)
[1] "matrix"
```
I think you may just need to pass `mesh.dsphere`? Although I'm maintainer, I've not workd on this part of the package.

**Comment by LoutK** [comment]
Just passing `mesh.dsphere` as a matrix is not working I'm afraid.

**Comment by davidcsterratt** [comment]
Whatever you pass, it needs to be a function, not a matrix.

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.
