### ISSUE TITLE
Error with Intel compilers

### ISSUE THREAD

**Issue by willpearse** [davidcsterratt/geometry#5]
Sorry to bother you, but I had trouble compiling using Intel compilers on my university's HPC. The problem was solved (thank you CHPC!) by commenting out part of the pre-processor directives in `qhull_a.h`:

```{C++}
105 //#if defined(__INTEL_COMPILER) && !defined(QHULL_OS_WIN) 
106 //template <typename T> 
107 //inline void qhullUnused(T &x) { (void)x; } 
108 //# define QHULL_UNUSED(x) qhullUnused(x); 
109 //#else 
110 # define QHULL_UNUSED(x) (void)x; 
111 //#endif 
```

...then everything worked like a charm.

**Comment by davidcsterratt** [comment]
Thanks for the report and sorry for the delay replying. Please could you try installing the latest version of geometry from github and let me know if the error is still there?
```
install.packages("devtools")
devtools::install_github("davidcsterratt/geometry", subdir="pkg")
```

**Comment by willpearse** [comment]
Don't apologise, I know what it's like! :D

Works like a charm. Thank you for fixing this!
