### ISSUE TITLE
Generalize `cart2sph()` to higher dimensions

### ISSUE THREAD

**Issue by Bisaloo** [davidcsterratt/geometry#51]
Hi,

I am interested in the [generalization of `cart2sph()` to an arbitrary number of dimensions](https://en.wikipedia.org/wiki/N-sphere#Spherical_coordinates). Since geometry already provides this conversion for 2 (`cart2pol()`) and 3 (`cart2sph()`) dimensions and since other functions from the same family (`cart2bary()`) already support an arbitrary number of dimensions, I believe this feature could belong here. I would understand if you believe this is out of scope but if you believe this is in scope, I can try and submit a PR for this!

**Comment by davidcsterratt** [comment]
Marking as won't fix for now, pending reply.

**Comment by Bisaloo** [comment]
Thanks for your answer.

I sent an email to the pracma maintainer today. I'll let you know if I receive an answer. In the meantime, I'm likely to write a draft generalized `cart2sph()` function for internal use in pavo (as part of https://github.com/rmaia/pavo/pull/181). It can be decided later where this function could live & be exported.

**Comment by hwborchers** [comment]
Thanks for your proposal of extending the 'cart2sph()' function in pracma. As David has rightfully said in the issues, pracma's main goal is to provide a Matlab-like numerical computation environment. Many pracma functions have been extended, or made more accurate or more stable in other R packages on CRAN. I really do welcome such efforts and see no problem in spreading functionality across several packages.
