### ISSUE TITLE
Feature Request: Show connectivity and interpolate element data onto nodes

### ISSUE THREAD

**Issue by michelk** [davidcsterratt/geometry#55]
I would like to interpolate element data onto nodes. Therefor information about the connectivity is necessary. 
Is there a fast algorithm to determine the elements per node? The ones I tried are far to slow for large meshes; at least in pure R.

**Comment by stla** [comment]
Do you mean you want to know which vertices are connected by an edge? Are you talking about the convex hull or Delaunay? 2D or 3D?

**Comment by davidcsterratt** [comment]
I don't fully understand this question. With the time elapsed since @michelk  asked, it's probably no longer relevant, so I'm closing this issue. Please feel free to reactivate.
