### ISSUE TITLE
mean

### ISSUE THREAD

**Issue by ggrothendieck** [davidcsterratt/geometry#56]
Would like a convhulln `mean` method to get centroid of convex hull.

**Comment by stla** [comment]
Hi, just take the means of the columns.

**Comment by stla** [comment]
Sorry, my comment is wrong: if there are some points more concentrated on a region, they will be overrepresented in the calculation of the mean.

You can use my package **cgalMeshes** to get the centroid of a mesh. And the dev version on Github can generate the mesh of a convex hull.

**Comment by davidcsterratt** [comment]
This isn't an issue that we need to fix, so I'm closing it.
