### ISSUE TITLE
Bug in geometry, tsearch function

### ISSUE THREAD

**Issue by WayneGitShell** [davidcsterratt/geometry#57]
Hi David and Jean-Romain

I'm seeing a potential bug in version 0.4.5 and some inconsistency in the behaviour of the function tsearch for different versions of geometry package. I’m using windows version 4.0.3 of R. 

See attached data and below code to reproduce the issue – see screenshot. 

When I add the argument method=”orig” it doesn’t report a bug but the results don’t look right and are different to the results using version 0.3.6. 

Hoping you can shed some light on this?

Thanks, 

Wayne

source("BugData.txt")
library(geometry)
packageVersion("geometry")
dn <- delaunayn(eval.df[, c("XCoord", "YCoord")])
tri <- tsearch(eval.df[, "XCoord"], eval.df[,  "YCoord"], dn, predred.df[, "XCoord"], predred.df[, "YCoord"], bary = T)

![tempPic](https://user-images.githubusercontent.com/61183826/109715275-5f108e80-7b9b-11eb-85fe-f3eb4662200b.jpg)

[BugData.txt](https://github.com/davidcsterratt/geometry/files/6071812/BugData.txt)

**Comment by davidcsterratt** [comment]
Sorry for the delay in getting to this. @Jean-Romain : would you have time to look at this?

**Comment by Jean-Romain** [comment]
Sure, i'll have a look a make few adjustment

**Comment by Jean-Romain** [comment]
There is indeed an issue that must be fixed in the Quadtree. However the method `orig` does work. If your result is not correct it is because your triangulation is not correct. Your points are regularly spaced and co-circular. The default triangulation is not correct you must pass the correct options

``` r
source("BugData.txt")
library(geometry)

dn <- delaunayn(eval.df[, c("XCoord", "YCoord")])
plot(eval.df[, c("XCoord", "YCoord")])
trimesh(dn, eval.df$XCoord, eval.df$YCoord, add = T)
```

![](https://i.imgur.com/xJfZcRi.png)

``` r

dn <- delaunayn(eval.df[, c("XCoord", "YCoord")], options = "Qx")
plot(eval.df[, c("XCoord", "YCoord")])
trimesh(dn, eval.df$XCoord, eval.df$YCoord, add = T)
```

![](https://i.imgur.com/lzTdRGq.png)

<sup>Created on 2024-08-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by WayneGitShell** [comment]
I've since  reverted back to method = "orig" for packageVersion("geometry")>'0.3.6'. 

Would you see any issues in the way it's been implemented here:
https://github.com/WayneGitShell/GWSDAT/blob/04f781b4991f0fb77f267d259636d3e4c9619c3b/R/interpBary.R#L75-L84 


Open to suggestions on best way to implement tsearch+options...

**Comment by Jean-Romain** [comment]
#73 fixes this issue
