### ISSUE TITLE
convhulln() receives QH6271 qhull precision error 

### ISSUE THREAD

**Issue by Huangmp1996** [davidcsterratt/geometry#58]
[p.csv](https://github.com/davidcsterratt/geometry/files/7014263/p.csv)
`library(geometry)`
`p <- read.csv("p.csv")`
`a <- convhulln(p,"FA")`

Then receive error below:

Error in convhulln(p, "FA") : 
  Received error code 5 from qhull. Qhull error:
QH6271 qhull precision error (qh_check_dupridge): wide merge (335628774511 times wider) due to duplicate ridge with nearly coincident points (0.33) between f35502016 and f35502013, merge dist 0.26, while processing p135
- Ignore error with option 'Q12'
- To be fixed in a later version of Qhull
- Vertex distance 0.33 is greater than 100 times maximum distance 7.7e-013
  Please report to bradb@shore.net with steps to reproduce and all output
ERRONEOUS FACET:
- f35502016
    - flags: bottom new seen mergehorizon dupridge mergeridge2
    - normal:   -0.7681  -0.1177  0.08241  0.02895  -0.0119   0.4809   0.2541  -0.2597  0.03146  -0.1555
    - offset: -0.5065939
    - vertices: p135(v375) p454(v343) p386(v313) p362(v309) p337(v298) p12(v252) p279(v199) p467(v140) p387(v131) p117(v98)
    - neighboring facets: f33585206 f35502013 f29524789 f35502015 f35502011 f29524782
    - ridges:
     - r157139
           vertices: p454(v343) p386(v313)

I use R version 4.1.0 (2021-05-18), Platform: x86_64-w64-mingw32/x64 (64-bit), Running under: Windows 10 x64 (build 19043).
How can I solve this problem?

**Comment by davidcsterratt** [comment]
I can reproduce this bug following an upgrade of the code to Qhull 8.0.2
```
QH6271 qhull precision error (qh_check_dupridge): wide merge (335628774511 times wider) due to duplicate ridge with nearly coincident points (0.33) between f35502016 and f35502013, merge dist 0.26, while processing p135
- Ignore error with option 'Q12'
- To be fixed in a later version of Qhull
- Vertex distance 0.33 is greater than 100 times maximum distance 7.7e-13
  Please report to bradb@shore.net with steps to reproduce and all output
ERRONEOUS FACET:
- f35502016
    - flags: bottom new seen mergehorizon dupridge mergeridge2
    - normal:   -0.7681  -0.1177  0.08241  0.02895  -0.0119   0.4809   0.2541  -0.2597  0.03146  -0.1555
    - offset: -0.5065939
    - vertices: p135(v375) p454(v343) p386(v313) p362(v309) p337(v298) p12(v252) p279(v199) p467(v140) p387(v131) p117(v98)
    - neighboring facets: f33585206 f35502013 f29524789 f35502015 f35502011 f29524782
    - ridges:
     - r157142
           vertices: p454(v343) p386(v31
```
@cbbarber Do you have any suggestions about Qhull flags that could help here?

**Comment by davidcsterratt** [comment]
I requested help too soon. Despite thinking it wouldn't help the `Qbb` flag allows the code to run without error with the code in the qhull-8.0.2 branch:
```
library(geometry)
p <- read.csv("p.csv")
a <- convhulln(p,"FA Qbb")
```
