### ISSUE TITLE
Negative neighbour IDs reported by delaunayn

### ISSUE THREAD

**Issue by stla** [davidcsterratt/geometry#60]
Hello,

  With these data one gets some negative neighbours in the Delaunay tessellation:

```r
> pts <- as.matrix(read.csv("pts.csv", header = TRUE))
> del <- geometry::delaunayn(pts, output.options = TRUE)
> del$neighbours[[899]]
[1]   1273    900 -18717    897
```

[pts.csv](https://github.com/davidcsterratt/geometry/files/7784018/pts.csv)

**Comment by davidcsterratt** [comment]
This is a feature of Qhull's `Fn` option:
http://www.qhull.org/html/qh-optf.htm#Fn

Basically, the negative numbers indicates a "facet" (="edge" in 2D or "face" in 3D) that doesn't have a neighbour, as happens along the edges of an outline.
