### ISSUE TITLE
Qhull does not take care of periodic boundary conditions?

### ISSUE THREAD

**Issue by Anny-tech** [davidcsterratt/geometry#62]
Hi, I am using the delaunayn function in this package, and since I am working on structure graphs of crystals its important that the delaunay traingulation be performed on my system considering the periodic boundary conditions. Hence, I wanted to know, is the delaunayn function taking care of that?

**Comment by davidcsterratt** [comment]
Sorry for the delay replying. No, the delaunayn function doesn't take care of that. deleaunayn is part of the [Qhull](https://www.qhull.org) library and you'd need to ask the author of that package. It seems that algorithms do exist for periodic boundary conditions, but not implemented in Qhull: https://github.com/scipy/scipy/issues/11858
