### ISSUE TITLE
Can't position labels above or below the plot limits

### ISSUE THREAD

**Issue by rdrivers** [davidcsterratt/geometry#70]
trimmest() calls plot.window with ylim = range(p[,2]) which doesn't leave enough room to add text above or below the plot.

X <- rbind(c(0,0), c(1,0), c(0,1))
trimesh(rbind(1:3), X)
text(X[,1], X[,2], labels = 1:3, pos = c(2,4,3)) # labels "1" and "3" don't appear

**Comment by davidcsterratt** [comment]
I think you can set up your plot window beforehand with the margins you desire, plot your points (e.g. `points(X[,1], X[,2])` and then call `trimesh` with the `add=TRUE` argument.
