### ISSUE TITLE
noRemap CRAN check

### ISSUE THREAD

**Issue by davidcsterratt** [davidcsterratt/geometry#71]
The CRAN maintainers write:

> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_geometry.html>.
>
> Specifically, please see the *noRemap* additional issue.
>
> Compilation fails when using _R_CXX_NO_REMAP_=true, which compiles C++
> code with R_NO_REMAP defined.  See chapter "The R API: entry points for
> C code" in "Writing R Extensions" for more information.
>
> It is planned that _R_CXX_NO_REMAP_=true will become the default in due
> course, ideally already for R 4.5.0, which in particular makes it
> necesssary that all CRAN packages with many strong reverse dependencies
> compile/install ok with the new default.
>
> Your package is among the ones with many strong reverse dependencies.
> We would thus really appreciate if you could provide a new version of
> your package as soon as possible which checks ok with
> _R_CXX_NO_REMAP_=true.
>
> You can verify that your package checks ok with _R_CXX_NO_REMAP_=true
> via R CMD check --as-cran using a current version of R-devel.
>
> Please correct before 2024-09-20 to safely retain your package on CRAN.

@Jean-Romain I'm wondering if you would have time to look at this? I expect I can do, but my C++ is a bit rusty.

**Comment by Jean-Romain** [comment]
Sure, I'll have a look. It should not be a big issue.

**Comment by davidcsterratt** [comment]
Many thanks for looking at this @Jean-Romain . 

I'm new to the NO_REMAP issue, but I'm wondering if we need to get rid of the `R.h` header and the `error()` and if instead we could just replace `error()` with `Rf_error()`? I'm thinking of prepending `Rf_` before all the internal functions, as suggested here:  https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-R-API_003a-entry-points-for-C-code

**Comment by davidcsterratt** [comment]
Apologies for the duplicate messages on this issue and the PR. I've decided for all the C functions to prepend `Rf_` to internal and error functions.
