### ISSUE TITLE
fast 2D tsearch using QuadTree

### ISSUE THREAD

**Issue by Jean-Romain** [davidcsterratt/geometry#9]
Hi

As said yesterday by email I guessed that function `tsearch` could be rewritten with a QuadTree. So I did it this morning in my own package. It is much more faster! For 200000 triangles and 10⁵ points it was 40 times faster.

```r
x = runif(1e5, 0, 100)
y = runif(1e5, 0, 100)
xi = runif(1e5, 10, 90)
yi = runif(1e5, 10, 90)

t = geometry::delaunayn(cbind(x,y))

geo = geometry::tsearch(x,y,t,xi,yi)
lid = lidR:::tsearch(x,y,t,xi,yi)
all(geo == lid)

microbenchmark::microbenchmark(geometry::tsearch(x,y,t,xi,yi), lidR:::tsearch(x,y,t,xi,yi), times =  3)
```

```
Unit: milliseconds
                               expr        min         lq      mean     median         uq       max neval
 geometry::tsearch(x, y, t, xi, yi) 11172.2146 11204.5871 11218.672 11236.9597 11241.9000 11246.840     3
    lidR:::tsearch(x, y, t, xi, yi)   266.2436   268.1801   268.901   270.1165   270.2298   270.343     3
```

With 10⁶ point the factor is times 70.

You can find the code [here](https://github.com/Jean-Romain/lidR/blob/devel/src/tsearch.cpp). I can make a pull request in `geometry` but it implies to put my QuadTree in your package. Not a problem. Tell me!

Cheers

**Comment by Jean-Romain** [comment]
In addition it can easily be parallelized.

**Comment by davidcsterratt** [comment]
Thanks very much for this work - this is a fantastic speed-up.

I have now got C code for the Qhull version almost going (see C_tsearchn in the tsearchn-qhull) branch (see Issue #6). Initial tests show it is about 3.3 times faster than the current tsearch, but 14 times slower than the Quadtree algorithm, so I think it would be great if you could incorporated the Quadtree algorithm into the geometry package, assuming that it is compliant with GPL2. 

The progress bar is "cool" but I would prefer for it to be turned off by default or not present at all - I think a number of users would find this a bit distracting. I note this will introduce a dependency on Rcpp, but I guess that's fine.

It would be great if you could run devtools::check() on the code you submit - there are a few tests for tsearch.

I might still persevere with the Qhull tsearchn code as it should work in 3+ dimensions.

**Comment by Jean-Romain** [comment]
Ok I'll work on incorporating QuadTree into geometry soon. If I add my own code myself I guess it's ok with licensing :smile: 

I will disable the progressbar. It is only a boolean. You will be able to add an option if you want. However the `Progress` object remain since it enable the user to interrupt the process.

It adds a dependency to Rcpp yes. Actually I can write it only with the standard library (QuadTree is written with `std` only) but Rcpp is a really really simple way to write C++ code into R. As you want, but not in C!

> It would be great if you could run devtools::check() on the code you submit - there are a few tests for tsearch.

Of course!

**Comment by davidcsterratt** [comment]
That would be great. Re licensing, I'm not sure if you need to add copyright notices to files now - it might be worth checking the R extensions manual. But in any case, make sure you add yourself to the DESCRIPTION file! 

I'm fine with Rcpp - there are many R packages that depend on it anyway, and I value speed and elegance of coding over an extra dependency.

Keeping the Progress object and disabling the progress bar sounds good.

Of course, as you're a package maintainer you know all about checking :-)

**Comment by Jean-Romain** [comment]
I did some mess with git because of my previous pull request. My previous PR was updated instead of creating a new PR and I failed in squashing my commits...  Anyway you have a button on github to squash commits when merging a PR.

**Comment by davidcsterratt** [comment]
Finally, I have managed to release v0.4.0 of geometry to CRAN.

**Comment by Jean-Romain** [comment]
I believed that will never happen ha ha  :+1:  

In my own package I now have a parallelized version of `tsearch` do you want it :wink: ? The gain is x2 to reach an easy x80 from the original version of `tsearch`

**Comment by davidcsterratt** [comment]
Yes, sorry it took so long :(-( There are a lot of hoops to jump through to get something on CRAN.
Yes, I'd be interested in the parallelised version of tsearch. If it's not difficult to put in a PR that would be great. Hopefullly it won't trigger any protection errors (https://github.com/davidcsterratt/geometry/issues/21)...
